### ISSUE TITLE
ChatRoom join unexpected keyword argument 'username'

### ISSUE THREAD

**Issue by derchrisuk** [panholt/err-backend-cisco-spark#11]
Hi,

I'm currently trying to setup errbot with your Cisco Spark backend.
Got it now working as it will connect to the API.
However, when entering a room id to join, i get the following:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 20, in callback_connect
    self._join_room(room)
  File "/usr/local/lib/python3.6/site-packages/errbot/core_plugins/chatRoom.py", line 34, in _join_room
    self.query_room(room).join(username=self.bot_config.CHATROOM_FN, password=password)
TypeError: join() got an unexpected keyword argument 'username'
````

Is this a problem with the backend?

**Comment by derchrisuk** [comment]
I tried another Spark backend using webhooks, which is able to connect to the room.
So I assume something is wrong with this backend.
